#sets the theme of the webpage
theme: jekyll-theme-minimal

#image displayed in the sidebar
logo: images/IMG_1646.jpg

# # #name of website and description
title: Gretchen Sileo
# description: Economics PhD Student @ Georgetown
email: gs907@georgetown.edu

#custom to ensure links to resources show up on page
include_links: true
