#sets the theme of the webpage
theme: jekyll-theme-minimal

#image displayed in the sidebar
logo: images/LargeHeadshot3.jpg

# # #name of website and description
title: Gretchen Sileo
# description: Assistant Professor of Economics @ Temple
email: gretchen.sileo@temple.edu

#custom to ensure links to resources show up on page
include_links: true
