#sets the theme of the webpage
theme: jekyll-theme-minimal

#image displayed in the sidebar
logo: images/LargeHeadshot.png

# #name of website and description
title: Gretchen Sileo
description: Economics PhD Candidate on the Job Market in Fall 2022

# #can set this as a round image or rectangular, default is round
# #round-avatar: false

