#sets the theme of the webpage
theme: jekyll-theme-minimal

#name of website and description
title: Gretchen Sileo
description: Economics PhD Candidate

#image displayed in the sidebar
avatar: "SmallHeadshot.png"

#can set this as a round image or rectangular, default is round
#round-avatar: false

#set the navigation bar links
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://www.gretchensileo.com/"
